version: "3.1"
services:
    www_le:
        build: .
        ports: 
            - "8081:80"
        volumes:
            - ./www:/var/www/html
        networks:
            - default 
volumes:
    persistent:
