version: "3.1"

services:
  pruebas_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - default

networks:
  default:
